// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AppKineticsSaveEditClient
{
	public partial class RootViewController : UIViewController
	{
		public RootViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
